// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataManagerBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataManagerBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SavePlayerData(string nickname)
        {
            await k_Service.CallModuleEndpointAsync(
                "PlayerDataManager",
                "SavePlayerData",
                new Dictionary<string, object>()
                {
                    {"nickname", nickname},
                });
        }

        public async Task<string> GetPlayerData(string playerId)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "PlayerDataManager",
                "GetPlayerData",
                new Dictionary<string, object>()
                {
                    {"playerId", playerId},
                });
        }
    }
}
